### PR TITLE
Added Player Number One

### PR DESCRIPTION
**Pull request by djphan**
Added Player Number One

### CODE REVIEW

**Comment by aljp** [comment]
_Ready Player One_ is already in the Sci Fi list, if you'd like to then perhaps just move that line to the fiction section

**Comment by mattjegan** [comment]
Though it's already in the list @djphan, it would be awesome if you could just add the author to the current entry as it is missing it.

**Comment by djphan** [comment]
Ah my apologies I can add the author to the list.

**Comment by mattjegan** [comment]
It's all good now, I fixed the PR and merged 😄  thanks for the help.

**Pull request merged**
